name: Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    all-tests:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@master
              with:
                  submodules: recursive
            # - uses: DoozyX/clang-format-lint-action@v0.13
            #   with:
            #       source: '.'
            #       extensions: 'hpp'
            #       clangFormatVersion: 14

            - name: cmake & make
              run: cmake -S ${{github.workspace}}/test -B ${{github.workspace}}/test/build && cmake --build ${{github.workspace}}/test/build

            - name: Run unit tests
              run: ${{github.workspace}}/test/build/geometry_test
