name: Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    all-tests:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@master
            - uses: lukka/get-cmake@latest
            - name: Run unit tests
              run: |
                  cmake -S . -B build
                  cmake --build build --config Debug -j
                  ctest --test-dir build --build-config Debug -j --output-on-failure